using System.Text;

namespace TradingBlockApiTestHarness.DTO.Orders
{
    public class OrderConfirmation
    {
        /// <summary>
        /// External reference id that you can use to differentiate multiple
        /// request responses sent within a short period of time from another.
        /// </summary>
        public int? ClientRefId { get; set; }

        /// <summary>
        /// Required for all follow-up requests for a given order, and
        /// required to be zero when placing new orders, this is the distinct
        /// order id in TradingBlock's system for this given order. This
        /// order id is generated by TradingBlock.
        /// </summary>
        public int OrderId { get; set; }

        /// <summary>
        /// Short description of the status of the request.
        /// </summary>
        public string Message { get; set; }

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder(base.ToString());
            sb.Append(" - ClientRefId:").Append(ClientRefId);
            sb.Append("; OrderId:").Append(OrderId);
            sb.Append("; Message:").Append(Message);
            return sb.ToString();
        }
    }
}
